# github action workflow name
name: modimal_CI
# workflow trigger
on:
    push:
        # add branch
        branches:
            - dev
            - 'feature/**'
            - 'fixbug/**'

jobs:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: action/checkout@V4.2.2
